---
# DNS configuration
- name: Remove stale zone files from default config
  file:
    path: /var/named/{{ item }}
    state: absent
  loop:
    - ocp4.example.com.db
    - ocp4.example.com.reverse.db
    - 172.25.254.zone

- name: Publish base named.conf
  copy:
    src: files/named.conf
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
  notify:
    - reload_named

- name: Publish base forward and reverse zones
  copy:
    src: files/254.25.172.in-addr.arpa.zone
    dest: /var/named/254.25.172.in-addr.arpa.zone
    mode: 0640
    owner: root
    group: named
  notify:
    - reload_named

# chronyd fixes
- name: Make sure chronyd is allowing time sync
  lineinfile:
    path: /etc/chrony.conf
    line: "allow 172.25.254.0/24"
    regexp: "^#?allow 172.25.*$"
    state: present
  notify:
    - restart_chronyd

# dhcpd configuration
- name: Publish base dhcpd.conf
  copy:
    src: files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart_dhcpd

- name: Backup stale grub.cfg from default config
  copy:
    src: /var/lib/tftpboot/grub.cfg-foundation
    dest: /var/lib/tftpboot/grub.cfg-f0.bkp
    remote_src: true

- name: Publish base grub.cfg
  copy:
    src: files/grub.cfg-foundation
    dest: /var/lib/tftpboot/grub.cfg-foundation
    mode: 0644
    owner: root

- name: Change HTTPD port
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    line: Listen 9000
    state: present
  notify: restart_httpd

- name: Change HTTPS port
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen'
    line: Listen 8443
    state: present
  notify: restart_httpd

- name: Install HAProxy dependencies
  ansible.builtin.yum:
    name: haproxy
    state: installed

- name: Enable SELinux Network ports on HAProxy
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_cache_port_t
    state: present
  loop:
    - 6443
    - 22623
    - 32700

- name: Enable SELinux Network ports on HAProxy
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop:
    - 6443
    - 22623
    - 32700

- name: Enable SELinux Network ports on HAProxy
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop:
    - 6443
    - 22623
    - 32700


- name: Enable Firewall Rules for HAProxy
  ansible.posix.firewalld:
    permanent: true
    port: "{{ item }}"
    state: enabled
  loop:
    - 6443/tcp
    - 80/tcp
    - 443/tcp
    - 22623/tcp
    - 32700/tcp
    - 9000/tcp
  notify: restart_firewall


  # haproxy configuration
- name: Publish base haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    owner: root
    group: root
  notify: restart_haproxy

  
# pxe boot config
# - name: Publish default PXE configuration file
#   copy:
#     src: files/default-pxe-config
#     dest: /var/lib/tftpboot/pxelinux.cfg/ocp4-default-pxe
#     mode: 0644
#     owner: root
#     group: root

# - name: Update symlink to the new PXE configuration file
#   file:
#     path: /var/lib/tftpboot/pxelinux.cfg/default
#     src: /var/lib/tftpboot/pxelinux.cfg/ocp4-default-pxe
#     state: link

- name: Make sure tftp.socket is enabled
  service:
    name: tftp.socket
    enabled: yes



...
