---
- name: Creating a PXE boot server
  hosts: default
  become: true
  gather_facts: false
  tasks:
  - name: Install tools
    ansible.builtin.yum:
      name:
      - bind
      - httpd
      - tftp-server
      - dhcp-server
      - python3-netaddr
      - p7zip
      state: present

  - name: Change HTTPD configuration
    # Comment
    ansible.builtin.lineinfile:
      regexp: "^Listen 80"
      line: "Listen 8080"
      path: /etc/httpd/conf/httpd.conf

  - name: Create directory to store bootloaders
    ansible.builtin.file:
      path: /var/lib/tftpboot/
      state: directory

  - name: Create directory to host images
    ansible.builtin.file:
      group: apache
      mode: "0755"
      owner: apache
      path: /var/www/html/openshift4/images
      state: directory

  - name: Create directory to host ignition files
    ansible.builtin.file:
      group: apache
      mode: "0755"
      owner: apache
      path: /var/www/html/openshift4/ignitions
      state: directory

  - name: Install tools
    ansible.builtin.yum:
      name: syslinux-tftpboot
      download_only: true
      download_dir:  /tmp/fedora
    register: tftpboot      
 

  - name: Convert tftpboot file to cpio
      Comment
    ansible.builtin.shell:
      chdir: /tmp/fedora
      cmd: "rpm2cpio {{ tftpboot.results[0] | regex_search('syslinux-tftpboot-[\\w\\-\\.]+') }}.rpm | cpio -idmv"
    
  - name: Copy pxelinux.0 file to the local tftp-server
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /var/lib/tftpboot/
      remote_src: true
    loop:
      - /tmp/fedora/tftpboot/pxelinux.0
      - /tmp/fedora/tftpboot/menu.c32

  - name: Configure new interface
    # Comment
    community.general.nmcli:
      autoconnect: true
      conn_name: eth1
      state: present
      type: ethernet
      ip4: 192.168.50.254




  
