---
- name: Prepare the foundation0 machine for deployment of SNO1 cluster
  hosts: default
  become: true
  gather_facts: false
  vars:
    node:
      ip: 192.168.50.1
      mac: a0-ce-c8-3a-90-37
      name: node
      role: SNO
      cluster: sno1
      online: yes
     
  roles:
    - role: fetch-resources
      tags: f0   
    - role: prep-f0
      tags: f0 
    - role: check-env
      tags: check
    - role: publish-infra
      tags: infra
    - role: deploy-infra
      tags: infra
    - role: prep-work
      tags: prep
...
