---
- name: Prepare the foundation0 machine for deployment of SNO1 cluster
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    node:
    #Update to an address that is part of the UCF physical environment.
      ip: 172.25.250.10
      #Update to use the MAC address from your own SNO host
      mac: 00-e0-4c-98-00-02
      name: node
      role: SNO
      cluster: sno1
      online: yes
      
  roles:
    - role: fetch-resources
      tags: f0   
    - role: prep-f0
      tags: f0 
    - role: check-env
      tags: check
    - role: publish-infra
      tags: infra
    - role: deploy-infra
      tags: infra
    - role: prep-work
      tags: prep
...
