---
- name: Prepare the utility VM for deployment of SNO1 cluster
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    node: 
      name: node
      ip: 172.25.254.230
        # adjust the MAC Address:        
      mac: "01-54-e1-ad-f2-84-3b"
        # Adjust the network adapter name
      network_adapter: enp2s0
      role: SNO
      cluster: sno1
      # adjust your disk accordingly  
      bootstrap_disk: /dev/sda
    bootstrap:
      name: bootstrap
      ip: 172.25.254.225
      mac: "52-54-00-00-00-fe"
      network_adapter: enp1s0
  pre_tasks:
    - name: Put the pull-secret onto kiosk VM
      become: no
      ansible.builtin.copy:
        src: files/pull-secret
        dest: /home/kiosk/pull-secret
        mode: 0600
      
  roles:
    - role: ws380-cleanup
      tags: cleanup
    - role: ws380-fetch-resources
      tags: fetch
    - role: ws380-prep-utility
      tags: prep
    - role: create-bootstrap-vm
      tags: prep
    - role: ws380-publish-infra
      tags: publish
    - role: check-env
      tags: check
    - role: deploy-infra
      tags: infra
    - role: prep-work
      tags: prep
  post_tasks:
    - name: Notify of completion
      pause:
        prompt: |
          **********************************************************************
          * THE WS380 CONFIGURATION ON UTILITY VMs IS NOW COMPLETE.            *
          *                                                                    *
          * Copies of kubeconfig and kubeadmin-password have been placed on    *
          * the workstation VM, in the home directory of user student.         *
          *                                                                    *
          * You can now proceed with the deployment of other workshop-specific *
          * settings by booting VMs and running other playbooks as per doc.    *
          **********************************************************************
        seconds: 1
...

