---
- name: Prepare router for deployment of SNO1 cluster
  hosts: openwrt
  become: true
  gather_facts: false
  vars:
    openwrt_system_hostname: router
    openwrt_system_zonename: America/New_York
    # Put your own public key file location here
    instructor_ssh_pubkey: ~/.ssh/github_work_rsa.pub
    # Put your own private key file location here
    instructor_ssh_privkey: ~/.ssh/github_work_rsa
    node: 
      name: node
      ip: 192.168.50.18
      mac: "01-54-e1-ad-f2-84-3b"
      network_adapter: enp2s0
      role: SNO
      cluster: sno1
      online: yes
  roles:
    # - role: ws380-cleanup
    #   tags: cleanup
    # - role: ws380-fetch-resources
    #   tags: fetch
    # - role: ws380-prep-utility
    #   tags: prep
    - role: openwrt-prep-work
      tags: prep    
    - role: nn708.openwrt.system
    - role: openwrt-publish-infra
      tags: publish
    # - role: check-env
    #   tags: check
    # - role: deploy-infra
    #   tags: infra
    # - role: prep-work
    #   tags: prep
  post_tasks:
    - name: Notify of completion
      pause:
        prompt: |
          **********************************************************************
          * THE WS380 CONFIGURATION ON UTILITY VMs IS NOW COMPLETE.            *
          *                                                                    *
          * Copies of kubeconfig and kubeadmin-password have been placed on    *
          * the workstation VM, in the home directory of user student.         *
          *                                                                    *
          * You can now proceed with the deployment of other workshop-specific *
          * settings by booting VMs and running other playbooks as per doc.    *
          **********************************************************************
        seconds: 1
...

