---
- name: Prepare the utility VM for deployment of SNO1 cluster
  hosts: default
  become: true
  gather_facts: false
  vars:
    node: 
      name: node
      ip: 172.25.254.1
      mac: "01-54-e1-ad-f2-84-3b"
      network_adapter: enp2s0
      role: SNO
      cluster: sno1
      online: yes
  roles:
    - role: ws380-cleanup
      tags: cleanup
    - role: ws380-fetch-resources
      tags: fetch
    - role: ws380-prep-utility
      tags: prep
    - role: ws380-publish-infra
      tags: publish
    - role: check-env
      tags: check
    - role: deploy-infra
      tags: infra
    - role: prep-work
      tags: prep
  post_tasks:
    - name: Notify of completion
      pause:
        prompt: |
          **********************************************************************
          * THE WS380 CONFIGURATION ON UTILITY VMs IS NOW COMPLETE.            *
          *                                                                    *
          * Copies of kubeconfig and kubeadmin-password have been placed on    *
          * the workstation VM, in the home directory of user student.         *
          *                                                                    *
          * You can now proceed with the deployment of other workshop-specific *
          * settings by booting VMs and running other playbooks as per doc.    *
          **********************************************************************
        seconds: 1
...

