---
# Extract the binaries
- name: Extract "oc"
  ansible.builtin.unarchive:
    src: "{{ binaries_directory }}/{{ tools.oc.bin }}"
    dest: /usr/local/bin/
    exclude:
      - README.md
      - kubectl
    remote_src: yes

- name: Copy coreos-installer into its place
  ansible.builtin.copy:
    src: "{{ binaries_directory }}/{{ tools.rhcos_inst.bin }}"
    dest: /usr/local/bin/coreos-installer
    remote_src: yes
    owner: root
    group: root
    mode: 0755

# Bash completion for finale
- name: Create completion files
  ansible.builtin.command:
    argv:
      - /bin/bash
      - -c
      - "{{ item }} completion bash > /etc/bash_completion.d/{{ item }}.completion"
  args:
    creates: /etc/bash_completion.d/{{ item }}
  loop:
    - oc
    - openshift-install

  

...
