---
# Extract the binaries
- name: Extract "oc"
  ansible.builtin.unarchive:
    src: "{{ binaries_directory }}/{{ tools.oc.bin }}"
    dest: /usr/local/bin/
    exclude:
      - README.md
      - kubectl
    remote_src: yes

- name: Copy coreos-installer into its place
  ansible.builtin.copy:
    src: "{{ binaries_directory }}/{{ tools.rhcos_inst.bin }}"
    dest: /usr/local/bin/coreos-installer
    remote_src: yes
    owner: root
    group: root
    mode: 0755

# Bash completion for finale
- name: Create completion files
  ansible.builtin.command:
    argv:
      - /bin/bash
      - -c
      - "oc completion bash > /etc/bash_completion.d/oc.completion"
  args:
    creates: /etc/bash_completion.d/oc
 

...
