---
# First make sure all target locations exist
- name: Create the download directories if not there yet
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ binaries_directory }}"
    - "{{ images_directory }}"
    - "/var/lib/tftpboot/pxelinux.cfg/"
    - "/var/lib/tftpboot/images/"

# Downloads often fail ("handshake timed out" blabla) so do them first.
- name: Download tools
  get_url:
    url: "{{ tools[item].url }}"
    dest: "{{ binaries_directory }}/{{ tools[item].bin }}"
  loop:
    - oc
    - openshift_install
    - butane
    - rhcos_inst

# - name: Download RHCOS live ISO
#   get_url:
#     url: "{{ rhcos_iso_url }}"
#     dest: "{{ images_directory }}"


# - name: Create symlink RHCOS ISO
#   ansible.builtin.file:
#     src: "{{ images_directory }}/{{ rhcos_iso_filename }}"
#     dest: "/var/lib/tftpboot/{{ rhcos_iso_filename }}"
#     state: link

- name: Download RHCOS rootfs
  get_url:
    url: "{{ rhcos_rootfs_url }}"
    dest: "{{ images_directory }}"

- name: Create symlink RHCOS rootfs
  ansible.builtin.file:
    src: "{{ images_directory }}/{{ rhcos_rootfs_filename }}"
    dest: "/var/lib/tftpboot/rhcos-rootfs.img"
    state: link


- name: Download RHCOS kernel
  get_url:
    url: "{{ rhcos_kernel_url }}"
    dest: "{{ images_directory }}"

- name: Create symlink RHCOS kernel
  ansible.builtin.file:
    src: "{{ images_directory }}/{{ rhcos_kernel_filename }}"
    dest: "/var/lib/tftpboot/rhcos-vmlinuz"
    state: link



- name: Download RHCOS initramfs
  get_url:
    url: "{{ rhcos_initramfs_url }}"
    dest: "{{ images_directory }}"

- name: Create symlink RHCOS initramfs
  ansible.builtin.file:
    src: "{{ images_directory }}/{{ rhcos_initramfs_filename }}"
    dest: "/var/lib/tftpboot/rhcos-initrd.img"
    state: link
    
...
