---
# First make sure all target locations exist
- name: Create the download directories if not there yet
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ binaries_directory }}"
    - "{{ images_directory }}"
    - "{{ ignitions_directory }}"
    - "/var/lib/tftpboot/pxelinux.cfg/"

- name: Install dependency needed by coreos-installer
  ansible.builtin.yum:
    name: compat-openssl11
    state: present


# Downloads often fail ("handshake timed out" blabla) so do them first.
- name: Download tools
  get_url:
    url: "{{ tools[item].url }}"
    dest: "{{ binaries_directory }}/{{ tools[item].bin }}"
  loop:
    - oc
    - rhcos_inst
    
    
...
