# DNS configuration
- name: Remove stale zone files from default config
  file:
    path: /var/named/{{ item }}
    state: absent
  loop:
  - ocp4.example.com.db
  - ocp4.example.com.reverse.db

- name: Publish base named.conf
  copy:
    src: files/named.conf
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
    backup: yes
  notify:
  - reload_named

- name: Publish base forward and reverse zones
  copy:
    src: files/{{ item }}.zone
    dest: /var/named/{{ item }}.zone
    mode: 0640
    owner: root
    group: named
    backup: yes
  loop:
  - ocp4.example.com
  - 172.25.254

- name: Configure DNS to load the published zones
  lineinfile:
    path: /etc/named.conf
    insertafter: "^# BEGIN ANSIBLE MANAGED DNS ZONES$"
    line: 'zone "{{ item }}" { type master; file "{{ item }}.zone"; allow-update { none; }; };'
    state: present
    backup: yes
  loop:
  - ocp4.example.com
  - 172.25.254
  notify:
  - reload_named

# chronyd fixes
- name: Make sure chronyd is allowing time sync
  lineinfile:
    path: /etc/chrony.conf
    line: "allow 172.25/16"
    regexp: "^#?allow 172.25.*$"
    state: present
    backup: yes
  notify:
  - restart_chronyd

# dhcpd configuration
- name: Publish base dhcpd.conf
  copy:
    src: files/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
  notify:
  - restart_dhcpd

# pxe boot config
- name: Publish default PXE configuration file
  copy:
    src: files/default-pxe-config
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    mode: 0644
    owner: root
    group: root
    backup: yes

# grub config
- name: Publish default GRUB configuration file
  copy:
    src: files/default-grub-config
    dest: /var/lib/tftpboot/grub.cfg-foundation
    mode: 0644
    owner: root
    group: root
    backup: yes


- name: Make sure tftp.socket is enabled
  service:
    name: tftp.socket
    enabled: yes
