---
# Checks that every prereq is in place:
#
# Services:
#  - DHCP
#  - TFTP
#  - DNS
#  - chronyd
#  - haproxy
#  - httpd
#
# Tools:
#  - openshift-install
#  - butane
#  - oc
#
# Files:
#  - ???
- name: Check services are running
  service:
    name: "{{ item }}"
    state: started
  loop:
    - dhcpd
    - tftp.socket
    - named
    - chronyd
    - httpd
    - haproxy

- name: Make sure all the tools are there
  file:
    path: /usr/local/bin/{{ item }}
    state: file
  loop:
    - openshift-install
    - butane
    - oc
...
