---
# Deploying:
#  - PXE config
#  - install-config.yaml
#  - network customization
#
# REQUIRES:
#  - variable "node" according to vms structure

    
# Create the OCP installation directory and populate it

- name: Delete dirs
  file:
    path: "{{ item }}"
    state: absent
  loop: 
    - /home/kiosk/{{ node.cluster }}


...
