---
- name: reload_named
  service:
    name: named
    enabled: yes
    state: reloaded

- name: restart_chronyd
  service:
    name: chronyd
    enabled: yes
    state: restarted

- name: restart_dhcpd
  service:
    name: dhcpd
    enabled: yes
    state: restarted

- name: restart_httpd
  service:
    name: httpd
    enabled: yes
    state: restarted
- name: restart_haproxy
  service:
    name: haproxy
    enabled: yes
    state: restarted    

- name: restart_firewall
  service:
    name: firewalld
    state: reloaded
...
